ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: http01
  hosts:
    - name: chartmuseum.51.250.85.21.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.51.250.85.21.nip.io.secret
