apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-server
        image: fastfighter92/paymentservice:v0.0.1
        env:
          - name: PORT
            value: "7887"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_DEBUGGER
            value: "1"
